version: '3'

services:
    frontend:
        build: ./frontend
        ports:
            - '80:80'
        depends_on:
            - backend 
    backend:
        build: ./backend
        env_file: 
            - secret.yml
        environment: 
            MAP_ENDPOINT: 'http://api.openweathermap.org/data/2.5'
            TARGET_CITY: 'Turku,fi'
        ports:
            - '9000:9000'